language: objective-c
gemfile:
  - Gemfile
before_script:
  - "bundle exec pod setup --silent"
  - "bundle exec rake pod:install -s"
  - export LANG=en_US.UTF-8
script: 
  - bundle exec rake spec
  - bundle exec rake frank
bump: 2
