// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CFNetwork/CFNetwork.h>
#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <QuartzCore/QuartzCore.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <UIKit/UIKit.h>

@interface Semaphore: NSObject
@end

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) applicationDidEnterBackground:(id) application;
-(IBAction) projects;
-(IBAction) load_model_data;
-(IBAction) write_model_data;

@end

@interface FavoriteProjectsController: UITableViewController

@property IBOutlet UITabBarItem * favorite_projects_button;
@property IBOutlet UITableView * favorites_table_view;

-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) show_instructions;

@end

@interface ProjectDetailsController: UIViewController

@property IBOutlet UIView * header;

-(IBAction) viewWillAppear:(id) animated;
-(IBAction) back:(id) sender;
-(IBAction) setup_header;

@end

@interface ProjectsController: UITableViewController

@property IBOutlet UITabBarItem * all_projects_button;
@property IBOutlet UITableView * projects_table_view;

-(IBAction) viewDidLoad;
-(IBAction) viewDidAppear:(id) animated;

@end

@interface ProjectsTabBarController: UITabBarController
-(IBAction) viewDidLoad;
-(IBAction) back:(id) sender;
-(IBAction) view_title;
-(IBAction) set_badge_count;
-(IBAction) project_counter:(id) method;

@end

@interface TokenController: UIViewController

@property IBOutlet UITextField * token_field;

-(IBAction) viewDidLoad;
-(IBAction) textFieldDidBeginEditing:(id) textField;
-(IBAction) textFieldDidEndEditing:(id) textField;
-(IBAction) textFieldShouldReturn:(id) textField;
-(IBAction) login:(id) sender;

@end

@interface Time: NSObject
-(IBAction) time_ago_in_words;

@end

@interface Branch: NSObject
-(IBAction) started_at;
-(IBAction) finished_at;
-(IBAction) brothers;
-(IBAction) finished_at_or_now;

@end

@interface Project: NSObject
-(IBAction) ordered_branches;
-(IBAction) master_branch;
-(IBAction) status;
-(IBAction) last_build;
-(IBAction) passed_branches;
-(IBAction) failed_branches;
-(IBAction) last_build_or_now;
-(IBAction) toggle_favorite;
-(IBAction) select_branch:(id) name;

@end

@interface Token: NSObject
@end

@interface ProjectsBuilder: NSObject
@end

@interface BranchCell: UITableViewCell

@property IBOutlet UILabel * branch_name;
@property IBOutlet UILabel * last_build;
@property IBOutlet UILabel * branch_status;
@property IBOutlet UIView * branch_status_background;
@property IBOutlet UIView * last_line_detail;

-(IBAction) color;

@end

@interface ProjectCell: UITableViewCell

@property IBOutlet UILabel * project_name;
@property IBOutlet UILabel * project_details;
@property IBOutlet UIButton * favorite_button;

-(IBAction) configure:(id) project;
-(IBAction) handle_favorite;
-(IBAction) configure_favorite_button;
-(IBAction) favorite_image;
-(IBAction) cell_color;

@end

@interface ProjectDetailsHeaderView: UIView

@property IBOutlet UILabel * project_name;
@property IBOutlet UILabel * last_build;
@property IBOutlet UILabel * project_status;
@property IBOutlet UILabel * number_of_branches;
@property IBOutlet UILabel * number_of_branches_failed;
@property IBOutlet UILabel * number_of_branches_passed;
@property IBOutlet UIView * project_status_background;

-(IBAction) configure:(id) project;

@end

