// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation Semaphore
@end

@implementation AppDelegate
@end

@implementation FavoriteProjectsController
@end

@implementation ProjectDetailsController
@end

@implementation ProjectsController
@end

@implementation ProjectsTabBarController
@end

@implementation TokenController
@end

@implementation Branch
@end

@implementation Project
@end

@implementation Token
@end

@implementation ProjectsBuilder
@end

@implementation BranchCell
@end

@implementation ProjectCell
@end

@implementation ProjectDetailsHeaderView
@end

