// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CFNetwork/CFNetwork.h>
#import <CoreData/CoreData.h>
#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <QuartzCore/QuartzCore.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <UIKit/UIKit.h>
#import <CoreData/CoreData.h>

@interface Semaphore: NSObject
@end

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface FavoriteProjectsController: UITableViewController

@property IBOutlet UITabBarItem * favorite_projects_button;
@property IBOutlet UITableView * favorites_table_view;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) show_instructions;
-(IBAction) refresh_projects;

@end

@interface ProjectDetailsController: UIViewController

@property IBOutlet UIView * header;

-(IBAction) viewWillAppear:(id) animated;
-(IBAction) back:(id) sender;
-(IBAction) setup_header;

@end

@interface ProjectsController: UITableViewController

@property IBOutlet UITabBarItem * all_projects_button;
@property IBOutlet UITableView * projects_table_view;

-(IBAction) viewDidLoad;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) refresh_projects;

@end

@interface ProjectsTabBarController: UITabBarController
-(IBAction) viewDidLoad;
-(IBAction) back:(id) sender;
-(IBAction) view_title;
-(IBAction) set_badge_count;
-(IBAction) handle_token_button;
-(IBAction) clean_projects;

@end

@interface TokenController: UIViewController

@property IBOutlet UITextField * token_field;

-(IBAction) viewDidLoad;
-(IBAction) textFieldShouldReturn:(id) textField;
-(IBAction) login:(id) sender;
-(IBAction) open_token_instructions;
-(IBAction) update_token;

@end

@interface Branch: CDQManagedObject
-(IBAction) human_building_date;
-(IBAction) brothers;

@end

@interface Project: CDQManagedObject
-(IBAction) status;
-(IBAction) last_build;
-(IBAction) master_branch;
-(IBAction) passed_branches;
-(IBAction) failed_branches;
-(IBAction) ordered_branches;
-(IBAction) toggle_favorite;
-(IBAction) favorite_to_bool;

@end

@interface Token: CDQManagedObject
@end

@interface ProjectUpdater: NSObject
@end

@interface ProjectsBuilder: NSObject
@end

@interface BranchCell: UITableViewCell

@property IBOutlet UILabel * branch_name;
@property IBOutlet UILabel * last_build;
@property IBOutlet UILabel * branch_status;
@property IBOutlet UIView * branch_status_background;
@property IBOutlet UIView * last_line_detail;

-(IBAction) color;
-(IBAction) count;

@end

@interface ProjectCell: UITableViewCell

@property IBOutlet UILabel * project_name;
@property IBOutlet UILabel * project_details;
@property IBOutlet UIButton * favorite_button;

-(IBAction) configure:(id) project;
-(IBAction) handle_favorite;
-(IBAction) parent_controller;
-(IBAction) configure_favorite_button;
-(IBAction) favorite_image;
-(IBAction) cell_color;

@end

@interface ProjectDetailsHeaderView: UIView

@property IBOutlet UILabel * project_name;
@property IBOutlet UILabel * last_build;
@property IBOutlet UILabel * project_status;
@property IBOutlet UILabel * number_of_branches;
@property IBOutlet UILabel * number_of_branches_failed;
@property IBOutlet UILabel * number_of_branches_passed;
@property IBOutlet UIView * project_status_background;

-(IBAction) configure:(id) project;

@end

