// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <QuartzCore/QuartzCore.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <UIKit/UIKit.h>

@interface Semaphore: NSObject
@end

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface FavoriteProjectsController: UITableViewController

@property IBOutlet UITabBarItem * favorite_projects_button;

@end

@interface ProjectDetailsController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) back:(id) sender;

@end

@interface ProjectsController: UITableViewController

@property IBOutlet UITabBarItem * all_projects_button;

-(IBAction) viewDidLoad;

@end

@interface ProjectsTabBarController: UITabBarController
-(IBAction) viewDidLoad;
-(IBAction) back:(id) sender;

@end

@interface TokenController: UIViewController

@property IBOutlet UITextField * token_field;

-(IBAction) viewDidLoad;
-(IBAction) textFieldDidBeginEditing:(id) textField;
-(IBAction) textFieldDidEndEditing:(id) textField;
-(IBAction) textFieldShouldReturn:(id) textField;
-(IBAction) login:(id) sender;

@end

@interface Branch: NSObject
-(IBAction) initialize:(id) attrs;
-(IBAction) started_at;
-(IBAction) finished_at;

@end

@interface Persistence: NSObject
-(IBAction) decode:(id) key;
-(IBAction) read:(id) key;
-(IBAction) delete:(id) key;

@end

@interface Project: NSObject
-(IBAction) build_branches:(id) branches_hash;
-(IBAction) color:(id) branch;
-(IBAction) last_build:(id) branch;
-(IBAction) select_branch:(id) name;
-(IBAction) color_status;

@end

