// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation Semaphore
@end

@implementation AppDelegate
@end

@implementation ProjectDetailsController
@end

@implementation ProjectsController
@end

@implementation TokenController
@end

@implementation Branch
@end

@implementation Persistence
@end

@implementation Project
@end

