// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation Semaphore
@end

@implementation AppDelegate
@end

@implementation AuthenticationCommand
@end

@implementation RefreshProjectsCommand
@end

@implementation BranchesController
@end

@implementation BuildsController
@end

@implementation FavoriteProjectsController
@end

@implementation ProjectsController
@end

@implementation ProjectsTabBarController
@end

@implementation TokenController
@end

@implementation RefreshControlHelper
@end

@implementation RemoteManager
@end

@implementation Branch
@end

@implementation Project
@end

@implementation Token
@end

@implementation BranchCell
@end

@implementation BranchesHeaderView
@end

@implementation BuildCell
@end

@implementation ProjectCell
@end

